CREATE TABLE `CONTACTS` (
  `ID` bigint(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `EMAIL_ID` varchar(255) NOT NULL,
  `MOBILE` varchar(15) DEFAULT NULL,
  `IS_DELETED` tinyint(1) unsigned zerofill DEFAULT '0',
  `CREATED_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL_ID_UNIQUE` (`EMAIL_ID`),
  KEY `NAME` (`NAME`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;